
version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python3.7
        auth:
          username: osetskiivadim1@gmail.com
          password: $DOCKERHUB_PASSWORD 
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: | 
            echo 'export PATH=$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip3 install --user -r requirments.txt
      - run:
          name: Run unit test
          command: | 
            pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests  
 
