
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python3.7.4
    steps:
        - checkout
        - run: pip3 install --user -r requirments.txt
        - run:
            name: Run unit test
            command: python3 -m unittest tests/test_server.py
        - store_test_result:
            path: test-reports
        - store_artificats:
            path: test-reports
