
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python3.7.4
    steps:
        - checkout
        - run: pip3 install --user -r requirments.txt
        - run:
            name: Run unit test
            command: pytest --junitxml=test-reports/junit.xml --html=test-reports/pytest_report.html --self-contained-html
        - store_test_result:
            path: test-reports
        - store_artificats:
            path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests  
